### ISSUE TITLE
Modules Page and Styling Changes

### ISSUE THREAD

**Issue by Konnor-Filip** [Konnor-Filip/Learn2Surf#68]
Below is a list of proposed changes to the modules and styling changes:
-Add Padding to MD text (50-100px)
-Add sub-module page
-Check jekyll rendering (everything is bolded?)
-Add accessible link to content hosted on GitHub. 
-Styling changes to the markdown page

**Comment by Konnor-Filip** [comment]
Comments from 12/1/2021:

Add another section that explanation 

Add formatting to Learning objectives

Bold verbiage 
Add sentence that prefaces the LO's
Time is valuable, need to see meat and potatoes front and center.
Headers and text size are important. 

Too many clicks for the files.
Resources and Materials - Rename "what you'll need"

Preview and Lesson plan outline

Header above the text
Module overview
Introduction/What this provides for you.
Explain what this module is, what it does for the teacher and what resources are provided for you.
Slide previewer. Embed google slides

Two Column Page
Column 1 becomes content
Column 2 becomes resources/pdfs/PowerPoints


Add module dropdown that becomes a menu entry.

**Comment by Konnor-Filip** [comment]
Added Mobile support for the whole website,
Updated individual module pages to the two column design. 
Updated LO's section
Resources can now be previewed
Added Dropdown to reduce clicks
Added content to google drive

**Comment by akbrousseau** [comment]
Styling Complete
